# Application
spring.application.name=solo-co
spring.profiles.active=local

# MyBatis
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.ssafy

# AWS S3
cloud.aws.s3.bucket=myapp-thumbnail-bucket
cloud.aws.credentials.accessKey=${AWS_ACCESSKEY}
cloud.aws.credentials.secretKey=${AWS_SECRETKEY}
cloud.aws.region.static=ap-northeast-2

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration-time=1800000
jwt.refresh-expiration-time=1209600000

# Upstage AI API Key
upstage.api.key=${UPSTAGE_API_KEY}
