# Application
spring.application.name=solo-co
spring.profiles.active=local

# MyBatis
mybatis.mapper-locations=classpath*:mappers/**/*.xml
mybatis.type-aliases-package=com.ssafy
mybatis.type-handlers-package=com.ssafy.global.util.mybatis

# AWS S3
cloud.aws.s3.bucket=${S3_BUCKET_NAME}
cloud.aws.credentials.accessKey=${AWS_ACCESSKEY}
cloud.aws.credentials.secretKey=${AWS_SECRETKEY}
cloud.aws.region.static=ap-northeast-2

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
# jwt.secret=${JWT_SECRET}
jwt.private-key-path=cert/private_key.pem
jwt.public-key-path=cert/public_key.pem
#jwt.access-expiration-time=1800000
#jwt.refresh-expiration-time=1209600000
jwt.access-expiration-time=86400000
jwt.refresh-expiration-time=1209600000

# OpenAI API
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

#Google Places API Key
google.places.api.key=${GOOGLE_PLACES_API_KEY}

# timeout setting - 5minute
server.tomcat.connection-timeout=300000